/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author NEKO
 */
public class GereciadorDeTelas extends javax.swing.JFrame {

    /**
     * Creates new form GereciadorDeTelas
     */
    public GereciadorDeTelas() {
        initComponents();
        Tela_InicialJpanel TI = new Tela_InicialJpanel();
        TI.setSize(content.getSize());
        TI.setLocation(0, 0);
        content.removeAll();
        content.add(TI);
        content.revalidate();
        content.repaint();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTelaPrincipal = new javax.swing.JMenu();
        jMenuMonitoramentoDetalhado = new javax.swing.JMenu();
        jMenuEstoque = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jMenuTelaPrincipal.setText("Tela Principal");
        jMenuTelaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTelaPrincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTelaPrincipal);

        jMenuMonitoramentoDetalhado.setText("Monitoramento Detalhado");
        jMenuMonitoramentoDetalhado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMonitoramentoDetalhadoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuMonitoramentoDetalhado);

        jMenuEstoque.setText("Estoque");
        jMenuEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEstoqueMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEstoque);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTelaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTelaPrincipalMouseClicked
        // TODO add your handling code here:
        Tela_InicialJpanel TI = new Tela_InicialJpanel();
        TI.setSize(content.getSize());
        TI.setLocation(0, 0);
        content.removeAll();
        content.add(TI);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jMenuTelaPrincipalMouseClicked

    private void jMenuMonitoramentoDetalhadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMonitoramentoDetalhadoMouseClicked
        // TODO add your handling code here:
        MonitoramentoDetalhadoJpanel MD = new MonitoramentoDetalhadoJpanel();
        MD.setSize(content.getSize());
        MD.setLocation(0, 0);
        content.removeAll();
        content.add(MD);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_jMenuMonitoramentoDetalhadoMouseClicked

    private void jMenuEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEstoqueMouseClicked
        // TODO add your handling code here:
        EstoqueJogosJpanel EJ = new EstoqueJogosJpanel();
        EJ.setSize(content.getSize());
        EJ.setLocation(0, 0);
        content.removeAll();
        content.add(EJ);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jMenuEstoqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GereciadorDeTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GereciadorDeTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GereciadorDeTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GereciadorDeTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GereciadorDeTelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenu jMenuMonitoramentoDetalhado;
    private javax.swing.JMenu jMenuTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
